version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine

  monitor.api:
    image: ${DOCKER_REGISTRY-}monitorapi
    build:
      context: .
      dockerfile: Services/Monitor/Monitor.API/Dockerfile
    depends_on:
      - rabbitmq

  consumer.api:
    image: ${DOCKER_REGISTRY-}consumerapi
    build:
      context: .
      dockerfile: Services/Consumer/Consumer.API/Dockerfile
    depends_on:
      - rabbitmq